### PR TITLE
wrapper: sync latest TiDB&CockroachDB changes

### PR DESCRIPTION
**Pull request by nieyy**
Sync with latest TiDB's KV interface changes.

PTAL @liugangnhm

### CODE REVIEW

**Comment by nieyy** [comment]
@liugangnhm , `.travis.yml` is not configured yet, please ignore the checks this time.

**Comment by ngaut** [comment]
Please fix CI broken.

**Comment by nieyy** [comment]
PTAL ag, @liugangnhm

**Comment by liugangnhm** [comment]
LGTM

**Pull request merged**
